name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instalacja Pythona 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      # Instalacja Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      # Instalacja zależności przy pomocy Poetry
      - name: Install dependencies
        run: |
          cd laboratorium11  # Przejście do katalogu, gdzie znajduje się pyproject.toml
          poetry install --no-interaction

  static_checks:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4

      # Ustawienie Pythona 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      # Instalacja Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      # Instalacja zależności
      - name: Install dependencies
        run: |
          cd laboratorium11  # Przejście do katalogu, gdzie znajduje się pyproject.toml
          poetry install --no-interaction

      # Linter z flake8
      - name: Lint with flake8
        run: |
          cd laboratorium11  # Upewnij się, że jesteś w odpowiednim katalogu
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Testy formatowania kodu
      - name: Check formatting with black
        run: |
          cd laboratorium11  # Upewnij się, że jesteś w odpowiednim katalogu
          poetry run black --check .

      # Testy bezpieczeństwa
      - name: Security check with safety
        run: |
          cd laboratorium11  # Upewnij się, że jesteś w odpowiednim katalogu
          poetry run safety check

  unit_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4

      # Ustawienie Pythona 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      # Instalacja Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      # Instalacja zależności
      - name: Install dependencies
        run: |
          cd laboratorium11  # Przejście do katalogu, gdzie znajduje się pyproject.toml
          poetry install --no-interaction

      # Uruchamianie testów jednostkowych z pytest
      - name: Run unit tests with pytest
        run: |
          cd laboratorium11  # Upewnij się, że jesteś w odpowiednim katalogu
          poetry run pytest

  poetry_tasks:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4

      # Ustawienie Pythona 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      # Instalacja Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      # Instalacja zależności
      - name: Instal
